/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDeliveriesRouteImport } from './routes/_authenticated/deliveries'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardIntegrationRouteImport } from './routes/_authenticated/dashboard.integration'
import { Route as AuthenticatedDashboardSelectAdAccountRouteImport } from './routes/_authenticated/dashboard.select-ad-account'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as ApiPublicTestEventRouteImport } from './routes/api/public/test-event'
import { Route as ApiPublicAccountDeleteRouteImport } from './routes/api/public/account/delete'
import { Route as ApiPublicAccountDisconnectMetaRouteImport } from './routes/api/public/account/disconnect-meta'
import { Route as ApiPublicCronCapiDispatcherRouteImport } from './routes/api/public/cron/capi-dispatcher'
import { Route as ApiPublicLeadsEnrichMissingRouteImport } from './routes/api/public/leads/enrich-missing'
import { Route as ApiPublicPagesConnectRouteImport } from './routes/api/public/pages/connect'
import { Route as ApiPublicPagesDisconnectRouteImport } from './routes/api/public/pages/disconnect'
import { Route as ApiPublicPagesRefreshRouteImport } from './routes/api/public/pages/refresh'
import { Route as ApiPublicWebhooksMetaLeadgenRouteImport } from './routes/api/public/webhooks/meta-leadgen'
import { Route as ApiPublicWebhooksStatusRouteImport } from './routes/api/public/webhooks/status'
import { Route as ApiPublicAuthMetaCallbackRouteImport } from './routes/api/public/auth/meta/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeliveriesRoute = AuthenticatedDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardIntegrationRoute =
  AuthenticatedDashboardIntegrationRouteImport.update({
    id: '/integration',
    path: '/integration',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSelectAdAccountRoute =
  AuthenticatedDashboardSelectAdAccountRouteImport.update({
    id: '/select-ad-account',
    path: '/select-ad-account',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPublicTestEventRoute = ApiPublicTestEventRouteImport.update({
  id: '/api/public/test-event',
  path: '/api/public/test-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAccountDeleteRoute = ApiPublicAccountDeleteRouteImport.update({
  id: '/api/public/account/delete',
  path: '/api/public/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAccountDisconnectMetaRoute =
  ApiPublicAccountDisconnectMetaRouteImport.update({
    id: '/api/public/account/disconnect-meta',
    path: '/api/public/account/disconnect-meta',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronCapiDispatcherRoute =
  ApiPublicCronCapiDispatcherRouteImport.update({
    id: '/api/public/cron/capi-dispatcher',
    path: '/api/public/cron/capi-dispatcher',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLeadsEnrichMissingRoute =
  ApiPublicLeadsEnrichMissingRouteImport.update({
    id: '/api/public/leads/enrich-missing',
    path: '/api/public/leads/enrich-missing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPagesConnectRoute = ApiPublicPagesConnectRouteImport.update({
  id: '/api/public/pages/connect',
  path: '/api/public/pages/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPagesDisconnectRoute =
  ApiPublicPagesDisconnectRouteImport.update({
    id: '/api/public/pages/disconnect',
    path: '/api/public/pages/disconnect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPagesRefreshRoute = ApiPublicPagesRefreshRouteImport.update({
  id: '/api/public/pages/refresh',
  path: '/api/public/pages/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMetaLeadgenRoute =
  ApiPublicWebhooksMetaLeadgenRouteImport.update({
    id: '/api/public/webhooks/meta-leadgen',
    path: '/api/public/webhooks/meta-leadgen',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksStatusRoute = ApiPublicWebhooksStatusRouteImport.update({
  id: '/api/public/webhooks/status',
  path: '/api/public/webhooks/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthMetaCallbackRoute =
  ApiPublicAuthMetaCallbackRouteImport.update({
    id: '/api/public/auth/meta/callback',
    path: '/api/public/auth/meta/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/data-deletion': typeof DataDeletionRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/integration': typeof AuthenticatedDashboardIntegrationRoute
  '/dashboard/select-ad-account': typeof AuthenticatedDashboardSelectAdAccountRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/public/test-event': typeof ApiPublicTestEventRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/public/account/delete': typeof ApiPublicAccountDeleteRoute
  '/api/public/account/disconnect-meta': typeof ApiPublicAccountDisconnectMetaRoute
  '/api/public/cron/capi-dispatcher': typeof ApiPublicCronCapiDispatcherRoute
  '/api/public/leads/enrich-missing': typeof ApiPublicLeadsEnrichMissingRoute
  '/api/public/pages/connect': typeof ApiPublicPagesConnectRoute
  '/api/public/pages/disconnect': typeof ApiPublicPagesDisconnectRoute
  '/api/public/pages/refresh': typeof ApiPublicPagesRefreshRoute
  '/api/public/webhooks/meta-leadgen': typeof ApiPublicWebhooksMetaLeadgenRoute
  '/api/public/webhooks/status': typeof ApiPublicWebhooksStatusRoute
  '/api/public/auth/meta/callback': typeof ApiPublicAuthMetaCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/data-deletion': typeof DataDeletionRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/integration': typeof AuthenticatedDashboardIntegrationRoute
  '/dashboard/select-ad-account': typeof AuthenticatedDashboardSelectAdAccountRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/public/test-event': typeof ApiPublicTestEventRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/api/public/account/delete': typeof ApiPublicAccountDeleteRoute
  '/api/public/account/disconnect-meta': typeof ApiPublicAccountDisconnectMetaRoute
  '/api/public/cron/capi-dispatcher': typeof ApiPublicCronCapiDispatcherRoute
  '/api/public/leads/enrich-missing': typeof ApiPublicLeadsEnrichMissingRoute
  '/api/public/pages/connect': typeof ApiPublicPagesConnectRoute
  '/api/public/pages/disconnect': typeof ApiPublicPagesDisconnectRoute
  '/api/public/pages/refresh': typeof ApiPublicPagesRefreshRoute
  '/api/public/webhooks/meta-leadgen': typeof ApiPublicWebhooksMetaLeadgenRoute
  '/api/public/webhooks/status': typeof ApiPublicWebhooksStatusRoute
  '/api/public/auth/meta/callback': typeof ApiPublicAuthMetaCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/data-deletion': typeof DataDeletionRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/deliveries': typeof AuthenticatedDeliveriesRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/dashboard/integration': typeof AuthenticatedDashboardIntegrationRoute
  '/_authenticated/dashboard/select-ad-account': typeof AuthenticatedDashboardSelectAdAccountRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/public/test-event': typeof ApiPublicTestEventRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/public/account/delete': typeof ApiPublicAccountDeleteRoute
  '/api/public/account/disconnect-meta': typeof ApiPublicAccountDisconnectMetaRoute
  '/api/public/cron/capi-dispatcher': typeof ApiPublicCronCapiDispatcherRoute
  '/api/public/leads/enrich-missing': typeof ApiPublicLeadsEnrichMissingRoute
  '/api/public/pages/connect': typeof ApiPublicPagesConnectRoute
  '/api/public/pages/disconnect': typeof ApiPublicPagesDisconnectRoute
  '/api/public/pages/refresh': typeof ApiPublicPagesRefreshRoute
  '/api/public/webhooks/meta-leadgen': typeof ApiPublicWebhooksMetaLeadgenRoute
  '/api/public/webhooks/status': typeof ApiPublicWebhooksStatusRoute
  '/api/public/auth/meta/callback': typeof ApiPublicAuthMetaCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/data-deletion'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/deliveries'
    | '/leads'
    | '/performance'
    | '/auth/callback'
    | '/dashboard/integration'
    | '/dashboard/select-ad-account'
    | '/dashboard/settings'
    | '/api/public/test-event'
    | '/dashboard/'
    | '/api/public/account/delete'
    | '/api/public/account/disconnect-meta'
    | '/api/public/cron/capi-dispatcher'
    | '/api/public/leads/enrich-missing'
    | '/api/public/pages/connect'
    | '/api/public/pages/disconnect'
    | '/api/public/pages/refresh'
    | '/api/public/webhooks/meta-leadgen'
    | '/api/public/webhooks/status'
    | '/api/public/auth/meta/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/data-deletion'
    | '/privacy'
    | '/terms'
    | '/deliveries'
    | '/leads'
    | '/performance'
    | '/auth/callback'
    | '/dashboard/integration'
    | '/dashboard/select-ad-account'
    | '/dashboard/settings'
    | '/api/public/test-event'
    | '/dashboard'
    | '/api/public/account/delete'
    | '/api/public/account/disconnect-meta'
    | '/api/public/cron/capi-dispatcher'
    | '/api/public/leads/enrich-missing'
    | '/api/public/pages/connect'
    | '/api/public/pages/disconnect'
    | '/api/public/pages/refresh'
    | '/api/public/webhooks/meta-leadgen'
    | '/api/public/webhooks/status'
    | '/api/public/auth/meta/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/data-deletion'
    | '/privacy'
    | '/terms'
    | '/_authenticated/dashboard'
    | '/_authenticated/deliveries'
    | '/_authenticated/leads'
    | '/_authenticated/performance'
    | '/auth/callback'
    | '/_authenticated/dashboard/integration'
    | '/_authenticated/dashboard/select-ad-account'
    | '/_authenticated/dashboard/settings'
    | '/api/public/test-event'
    | '/_authenticated/dashboard/'
    | '/api/public/account/delete'
    | '/api/public/account/disconnect-meta'
    | '/api/public/cron/capi-dispatcher'
    | '/api/public/leads/enrich-missing'
    | '/api/public/pages/connect'
    | '/api/public/pages/disconnect'
    | '/api/public/pages/refresh'
    | '/api/public/webhooks/meta-leadgen'
    | '/api/public/webhooks/status'
    | '/api/public/auth/meta/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DataDeletionRoute: typeof DataDeletionRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiPublicTestEventRoute: typeof ApiPublicTestEventRoute
  ApiPublicAccountDeleteRoute: typeof ApiPublicAccountDeleteRoute
  ApiPublicAccountDisconnectMetaRoute: typeof ApiPublicAccountDisconnectMetaRoute
  ApiPublicCronCapiDispatcherRoute: typeof ApiPublicCronCapiDispatcherRoute
  ApiPublicLeadsEnrichMissingRoute: typeof ApiPublicLeadsEnrichMissingRoute
  ApiPublicPagesConnectRoute: typeof ApiPublicPagesConnectRoute
  ApiPublicPagesDisconnectRoute: typeof ApiPublicPagesDisconnectRoute
  ApiPublicPagesRefreshRoute: typeof ApiPublicPagesRefreshRoute
  ApiPublicWebhooksMetaLeadgenRoute: typeof ApiPublicWebhooksMetaLeadgenRoute
  ApiPublicWebhooksStatusRoute: typeof ApiPublicWebhooksStatusRoute
  ApiPublicAuthMetaCallbackRoute: typeof ApiPublicAuthMetaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deliveries': {
      id: '/_authenticated/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof AuthenticatedDeliveriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/integration': {
      id: '/_authenticated/dashboard/integration'
      path: '/integration'
      fullPath: '/dashboard/integration'
      preLoaderRoute: typeof AuthenticatedDashboardIntegrationRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/select-ad-account': {
      id: '/_authenticated/dashboard/select-ad-account'
      path: '/select-ad-account'
      fullPath: '/dashboard/select-ad-account'
      preLoaderRoute: typeof AuthenticatedDashboardSelectAdAccountRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/public/test-event': {
      id: '/api/public/test-event'
      path: '/api/public/test-event'
      fullPath: '/api/public/test-event'
      preLoaderRoute: typeof ApiPublicTestEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/account/delete': {
      id: '/api/public/account/delete'
      path: '/api/public/account/delete'
      fullPath: '/api/public/account/delete'
      preLoaderRoute: typeof ApiPublicAccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/account/disconnect-meta': {
      id: '/api/public/account/disconnect-meta'
      path: '/api/public/account/disconnect-meta'
      fullPath: '/api/public/account/disconnect-meta'
      preLoaderRoute: typeof ApiPublicAccountDisconnectMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/capi-dispatcher': {
      id: '/api/public/cron/capi-dispatcher'
      path: '/api/public/cron/capi-dispatcher'
      fullPath: '/api/public/cron/capi-dispatcher'
      preLoaderRoute: typeof ApiPublicCronCapiDispatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads/enrich-missing': {
      id: '/api/public/leads/enrich-missing'
      path: '/api/public/leads/enrich-missing'
      fullPath: '/api/public/leads/enrich-missing'
      preLoaderRoute: typeof ApiPublicLeadsEnrichMissingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pages/connect': {
      id: '/api/public/pages/connect'
      path: '/api/public/pages/connect'
      fullPath: '/api/public/pages/connect'
      preLoaderRoute: typeof ApiPublicPagesConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pages/disconnect': {
      id: '/api/public/pages/disconnect'
      path: '/api/public/pages/disconnect'
      fullPath: '/api/public/pages/disconnect'
      preLoaderRoute: typeof ApiPublicPagesDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pages/refresh': {
      id: '/api/public/pages/refresh'
      path: '/api/public/pages/refresh'
      fullPath: '/api/public/pages/refresh'
      preLoaderRoute: typeof ApiPublicPagesRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/meta-leadgen': {
      id: '/api/public/webhooks/meta-leadgen'
      path: '/api/public/webhooks/meta-leadgen'
      fullPath: '/api/public/webhooks/meta-leadgen'
      preLoaderRoute: typeof ApiPublicWebhooksMetaLeadgenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/status': {
      id: '/api/public/webhooks/status'
      path: '/api/public/webhooks/status'
      fullPath: '/api/public/webhooks/status'
      preLoaderRoute: typeof ApiPublicWebhooksStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/meta/callback': {
      id: '/api/public/auth/meta/callback'
      path: '/api/public/auth/meta/callback'
      fullPath: '/api/public/auth/meta/callback'
      preLoaderRoute: typeof ApiPublicAuthMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardIntegrationRoute: typeof AuthenticatedDashboardIntegrationRoute
  AuthenticatedDashboardSelectAdAccountRoute: typeof AuthenticatedDashboardSelectAdAccountRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardIntegrationRoute:
      AuthenticatedDashboardIntegrationRoute,
    AuthenticatedDashboardSelectAdAccountRoute:
      AuthenticatedDashboardSelectAdAccountRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedDeliveriesRoute: typeof AuthenticatedDeliveriesRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedDeliveriesRoute: AuthenticatedDeliveriesRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DataDeletionRoute: DataDeletionRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiPublicTestEventRoute: ApiPublicTestEventRoute,
  ApiPublicAccountDeleteRoute: ApiPublicAccountDeleteRoute,
  ApiPublicAccountDisconnectMetaRoute: ApiPublicAccountDisconnectMetaRoute,
  ApiPublicCronCapiDispatcherRoute: ApiPublicCronCapiDispatcherRoute,
  ApiPublicLeadsEnrichMissingRoute: ApiPublicLeadsEnrichMissingRoute,
  ApiPublicPagesConnectRoute: ApiPublicPagesConnectRoute,
  ApiPublicPagesDisconnectRoute: ApiPublicPagesDisconnectRoute,
  ApiPublicPagesRefreshRoute: ApiPublicPagesRefreshRoute,
  ApiPublicWebhooksMetaLeadgenRoute: ApiPublicWebhooksMetaLeadgenRoute,
  ApiPublicWebhooksStatusRoute: ApiPublicWebhooksStatusRoute,
  ApiPublicAuthMetaCallbackRoute: ApiPublicAuthMetaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
